### ISSUE TITLE
未知的原因导致乱码

### ISSUE THREAD

**Issue by imbytecat** [jozhn/Bigfa#12]
乱码的效果见 [我的博客的一篇文章](https://new.imbytecat.com/posts/164/)，一开始我还以为是我的问题，但是好几个页面都是这样，而换了一个主题就没有问题，请问这是什么情况。

![](https://i.loli.net/2020/05/10/6JYdNHBEivknFXm.png)

**Comment by imbytecat** [comment]
比较神奇的是当我把主题设置的「CDN 镜像地址」设置为：`https://cdn.jozhn.com/` 时，居然就显示正常了，我怀疑 GitHub 上的这个 2.0 版本在打包一些文件的时候出现了问题。（

**Comment by jozhn** [comment]
字体忘记传了，更新一下
