### ISSUE TITLE
其实真心建议作者弄一个归档功能

### ISSUE THREAD

**Issue by ghost** [jozhn/Bigfa#13]
RT，作者如何看待？归档比起传统翻页也好还是ajax加载更多文章也好，都要好很多

**Comment by jozhn** [comment]
确实可以，等有空搞一下，这个应该很快

**Comment by ghost** [comment]
> 确实可以，等有空搞一下，这个应该很可能

是的，没啥难度。另一个就是，这个主题我用过试了一下，ajax加载貌似有点问题，手动点击浏览器返回的时候会直接跳转到首页来。

**Comment by jozhn** [comment]
加了https://github.com/jozhn/Bigfa/commit/a5e7382b70a876457868bae6bc820b7a681de18c
