### ISSUE TITLE
网站进不去了，一直显示正在加载

### ISSUE THREAD

**Issue by DereenMec** [jozhn/Bigfa#2]
感觉是不是引用的哪个Js文件挂了，你的网站也进不去显示正在连接cdn.bootcss.com

**Comment by DereenMec** [comment]
john，就是这个网站挂了，建议快换源把

**Comment by jozhn** [comment]
之前确实是bootcss挂了，不过他们301到cloudflare的源了，我这里是没有问题的，你现在访问有问题吗？

**Comment by DereenMec** [comment]
> 之前确实是bootcss挂了，不过他们301到cloudflare的源了，我这里是没有问题的，你现在访问有问题吗？

我这里访问你的博客（dearjohn.cn）还是进不去，可能跟网络运营商有关系，我是陕西移动，我上网搜了下换了baomitu的源- -

**Comment by jozhn** [comment]
我这好像没问题，17ce.com测试全国也没问题~
